config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }

  get "users/:id/appointments", to: "users#appointments", as: "user_appointments"

  resources :services

  resources :appointments do
    collection do
      get "available_dates_and_times"
    end
    member do
      get :confirm
    end
  end

  resources :users do
    resources :appointments, only: [ :new, :create ], controller: "appointments"
  end

  get "appointments/phone", to: "appointments#by_phone", as: "appointments_by_phone"
  resources :disponibilidades

  get "/admin", to: "admin#index"
  resources :clients

  root to: "home#index"
end

app/models/service.rb
class Service < ApplicationRecord
  def duration_hours
    (duration || 0) / 60
  end

  def duration_minutes
    (duration || 0) % 60
  end

  def duration_hours=(hours)
    @duration_hours = hours.to_i
  end

  def duration_minutes=(minutes)
    @duration_minutes = minutes.to_i
  end

  before_save :calculate_duration

  def formatted_duration
    hours = duration_hours
    minutes = duration_minutes
    "#{hours} horas e #{minutes} minutos"
  end

  private

  def calculate_duration
    self.duration = (@duration_hours.to_i * 60) + @duration_minutes.to_i
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin
  before_action :set_service, only: [ :show, :edit, :update, :destroy ]

  def index
    @services = Service.all
  end

  def new
    @service = Service.new
  end

  def create
    @service = Service.new(service_params)
    if @service.save
      redirect_to services_path, notice: "Serviço criado com sucesso."
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @service.update(service_params)
      redirect_to services_path, notice: "Serviço atualizado com sucesso."
    else
      render :edit
    end
  end

  def destroy
    @service.destroy
    redirect_to services_path, notice: "Serviço excluído com sucesso."
  end

  private

  def set_service
    @service = Service.find(params[:id])
  end

  def service_params
    params.require(:service).permit(:name, :description, :duration_hours, :duration_minutes)
  end

  def check_admin
    redirect_to(root_path, alert: "Você não tem permissão para acessar esta página.") unless current_user.admin?
  end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/edit.html.erb
<h1><%= action_name == 'new' ? 'Novo Serviço' : 'Editar Serviço' %></h1>
  <%= form_with(model: @service, local: true) do |form| %>
      <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name %>
      </div>
      <div class="field">
        <%= form.label :description %>
        <%= form.text_area :description %>
      </div>
      <div class="field">
        <%= form.label :duration_hours, "Duração (horas)" %>
        <%= form.number_field :duration_hours, value: @service.duration_hours %>
      </div>
      <div class="field">
        <%= form.label :duration_minutes, "Duração (minutos)" %>
        <%= form.number_field :duration_minutes, value: @service.duration_minutes %>
      </div>
      <div class="actions">
        <%= form.submit %>
      </div>
<% end %>

app/views/services/index.html.erb
<h1>Serviços</h1>
<%= link_to 'Voltar', admin_path, class: 'btn btn-segundary' %>
<%= link_to 'Novo Serviço', new_service_path, class: 'btn btn-primary' %>
<table class="table">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descrição</th>
      <th>Duração</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.name %></td>
        <td><%= service.description %></td>
        <td><%= service.formatted_duration %> minutos</td>
        <td>
          <%= link_to 'Editar', edit_service_path(service), class: 'btn btn-warning' %>
          <%= button_to 'Excluir', service_path(service), method: :delete, data: { turbo_confirm: "Você tem certeza?" }, class: 'btn btn-danger btn-sm' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/services/new.html.erb
<h1><%= action_name == 'new' ? 'Novo Serviço' : 'Editar Serviço' %></h1>
  <%= form_with(model: @service, local: true) do |form| %>
      <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name %>
      </div>
      <div class="field">
        <%= form.label :description %>
        <%= form.text_area :description %>
      </div>
      <div class="field">
        <%= form.label :duration_hours, "Duração (horas)" %>
        <%= form.number_field :duration_hours, value: @service.duration_hours %>
      </div>
      <div class="field">
        <%= form.label :duration_minutes, "Duração (minutos)" %>
        <%= form.number_field :duration_minutes, value: @service.duration_minutes %>
      </div>
      <div class="actions">
        <%= form.submit %>
      </div>
<% end %>

app/views/services/show.html.erb
<h1>Detalhes do Serviço</h1>

<p>
  <strong>Nome:</strong>
  <%= @service.name %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @service.description %>
</p>

<p>
  <strong>Duração:</strong>
  <%= @service.formatted_duration %> minutos
</p>

<%= link_to 'Editar', edit_service_path(@service), class: 'btn btn-warning' %>
<%= link_to 'Voltar', services_path, class: 'btn btn-secondary' %>