config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }

  get "users/:id/appointments", to: "users#appointments", as: "user_appointments"

  resources :services

  resources :appointments do
    collection do
      get "available_dates_and_times"
    end
    member do
      get :confirm
    end
  end

  resources :users do
    resources :appointments, only: [ :new, :create ], controller: "appointments"
  end

  get "appointments/phone", to: "appointments#by_phone", as: "appointments_by_phone"
  resources :disponibilidades

  get "/admin", to: "admin#index"
  resources :clients

  root to: "home#index"
end

app/views/admin/index.html.erb
<!-- app/views/admin/index.html.erb -->
<div class="container">
  <div class="d-flex justify-content-between align-items-center mb-4">
    <h2>Profissionais</h2>
    <div>
      <%= link_to "Cadastrar Profissional", new_user_registration_path, class: 'btn btn-primary' %>
      <%= link_to "Serviços", services_path, class: 'btn btn-primary' %>
    </div>
  </div>

  <table class="table table-striped table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Nome</th>
        <th>Email</th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
      <% @professionals.each do |professional| %>
        <tr>
          <td><%= professional.name %></td>
          <td><%= professional.email %></td>
          <td>
            <div class="btn-group" role="group">
              <%= link_to 'Agendamentos', user_appointments_path(professional), class: 'btn btn-info btn-sm' %>
              <%= link_to 'Editar', edit_user_path(professional), class: 'btn btn-secondary btn-sm' %>
              <%= button_to 'Excluir', user_path(professional), method: :delete, data: { turbo_confirm: "Você tem certeza?" }, class: 'btn btn-danger btn-sm' %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>