config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }

  get "users/:id/appointments", to: "users#appointments", as: "user_appointments"

  resources :services

  resources :appointments do
    collection do
      get "available_dates_and_times"
    end
    member do
      get :confirm
    end
  end

  resources :users do
    resources :appointments, only: [ :new, :create ], controller: "appointments"
  end

  get "appointments/phone", to: "appointments#by_phone", as: "appointments_by_phone"
  resources :disponibilidades

  get "/admin", to: "admin#index"
  resources :clients

  root to: "home#index"
end

app/models/disponibilidade.rb
class Disponibilidade < ApplicationRecord
  belongs_to :profissional, class_name: "User", foreign_key: "user_id"
end

app/controllers/disponibilidades_controller.rb
class DisponibilidadesController < ApplicationController
  before_action :authenticate_user! # Assumindo que você usa Devise para Admin
  before_action :set_disponibilidade, only: [ :show, :edit, :update, :destroy ]
  before_action :set_professionals, only: [ :new, :edit, :create, :update ]

  def index
    @disponibilidades = Disponibilidade.all
  end

  def show
  end

  def new
    @disponibilidade = Disponibilidade.new
    @professionals = User.where(admin: false)
  end

  def edit
  end

  def create
    @disponibilidade = Disponibilidade.new(disponibilidade_params)

    if @disponibilidade.save
      redirect_to @disponibilidade, notice: "Disponibilidade criada com sucesso."
    else
      render :new
    end
  end

  def update
    if @disponibilidade.update(disponibilidade_params)
      redirect_to @disponibilidade, notice: "Disponibilidade atualizada com sucesso."
    else
      render :edit
    end
  end

  def destroy
    @disponibilidade.destroy
    redirect_to disponibilidades_url, notice: "Disponibilidade excluída com sucesso."
  end

  private

  def set_professionals
    @professionals = User.all
  end

  private
    def set_disponibilidade
      @disponibilidade = Disponibilidade.find(params[:id])
    end

    def disponibilidade_params
      params.require(:disponibilidade).permit(:user_id, :data, :horario)
    end
end

app/views/disponibilidades/_form.html.erb
<%= form_with(model: [@professional, @disponibilidade ], local: true) do |form| %>
  <% if @disponibilidade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@disponibilidade.errors.count, "error") %> prohibited this disponibilidade from being saved:</h2>

      <ul>
        <% @disponibilidade.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :professional, "Profissional" %>
    <%= form.collection_select :user_id, @professionals, :id, :name, prompt: "Selecione um profissional" %>
  </div>

  <div class="field">
    <%= form.label :data %>
    <%= form.text_field :data, class: "input input--datepicker", data: { 
                         controller: "datepicker",
                         datepicker_date_format_value: "Y-m-d"
                       },
                       placeholder: "Selecione uma data" %>
  </div>

  <div class="field">
    <%= form.label :horario %>
    <%= form.time_select :horario %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/disponibilidades/edit.html.erb
<h1>Editing Disponibilidade</h1>

<%= render 'form', disponibilidade: @disponibilidade %>

<%= link_to 'Show', @disponibilidade %> |
<%= link_to 'Back', disponibilidades_path %>

app/views/disponibilidades/index.html.erb
<h1>Disponibilidades</h1>

<table>
  <thead>
    <tr>
      <th>Profissional</th>
      <th>Data</th>
      <th>Horário</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @disponibilidades.each do |disponibilidade| %>
      <tr>
        <td><%= disponibilidade.profissional.name %></td>
        <td><%= disponibilidade.data %></td>
        <td><%= disponibilidade.horario.strftime("%H:%M") %></td>
        <td>
          <%= link_to 'Show', disponibilidade %>
          <%= link_to 'Edit', edit_disponibilidade_path(disponibilidade) %>
          <%= link_to 'Destroy', disponibilidade, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Disponibilidade', new_disponibilidade_path %>

app/views/disponibilidades/new.html.erb
<h1>New Disponibilidade</h1>

<%= render 'form', disponibilidade: @disponibilidade %>

<%= link_to 'Back', disponibilidades_path %>

app/views/disponibilidades/show.html.erb
<p>
  <strong>Profissional:</strong>
  <%= @disponibilidade.profissional.name %>
</p>

<p>
  <strong>Data:</strong>
  <%= @disponibilidade.data %>
</p>

<p>
  <strong>Horário:</strong>
  <%= @disponibilidade.horario.strftime("%H:%M") %>
</p>

<%= link_to 'Edit', edit_disponibilidade_path(@disponibilidade) %> |
<%= link_to 'Back', disponibilidades_path %>