config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }

  get "users/:id/appointments", to: "users#appointments", as: "user_appointments"

  resources :services

  resources :appointments do
    collection do
      get "available_dates_and_times"
    end
    member do
      get :confirm
    end
  end

  resources :users do
    resources :appointments, only: [ :new, :create ], controller: "appointments"
  end

  get "appointments/phone", to: "appointments#by_phone", as: "appointments_by_phone"
  resources :disponibilidades

  get "/admin", to: "admin#index"
  resources :clients

  root to: "home#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :phone, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :name, presence: true, uniqueness: true

  scope :professionals, -> { where(admin: false) }

  has_many :appointments_as_professional, class_name: "Appointment", foreign_key: "user_id"
  has_many :appointments_as_client, class_name: "Appointment", foreign_key: "client_id"
  has_many :services
  has_many :disponibilidades

  before_save :format_phone_number

  def admin?
    self.admin
  end

  def professional?
    !self.admin
  end

  def email_required?
    true
  end

  def will_save_change_to_email?
    true
  end

  private

  def format_phone_number
    self.phone = phone.gsub(/\D/, "")
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  skip_before_action :require_no_authentication, only: [ :new, :create ]

  def new
    super
  end

  def create
    build_resource(sign_up_params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        redirect_to admin_path # Redireciona para o painel de admin
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        redirect_to admin_path # Redireciona para o painel de admin
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def create
    super do |resource|
      if resource.admin?
        redirect_to admin_path and return
      else
        redirect_to user_appointments_path(resource) and return
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [ :edit, :update, :destroy, :appointments ]


  def create
    @user = User.new(user_params)
    if @user.save
      create_appointments_for_services(@user)
      redirect_to admin_path, notice: "Profissional criado com sucesso."
    else
      render :new
    end
  end
  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to admin_path, notice: "Usuário atualizado com sucesso."
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_path, notice: "Usuário excluído com sucesso."
  end

  def appointments
    @appointments = @user.appointments_as_professional
  end

  private

  def create_appointments_for_services(user)
    user.services.each do |service|
      # Lógica para criar horários disponíveis na agenda do profissional
      # com base na duração do serviço
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
    params.require(:user).permit(:name, :email, :phone, :password, :password_confirmation)
  end
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/appointments.html.erb
<!-- app/views/users/appointments.html.erb -->
<h1>Agendamentos de <%= @user.name %></h1>

<table class="table">
  <thead>
    <tr>
      <th>Data</th>
      <th>Cliente</th>
      <th>Telefone</th>
      <th>Ações</th>
    </tr>
  </thead>

  <%= link_to 'Voltar', admin_path, class: 'btn-secundary' if current_user.admin? %>
  <%= link_to 'Agendar Cliente', new_user_appointment_path(@user), class: 'btn btn-primary' %><br />

  <tbody id="appointments">
  <% @appointments.each do |appointment| %>
    <tr id="<%= dom_id(appointment) %>">
      <td><%= appointment.date %></td>
      <td><%= appointment.client.name %></td>
      <td><%= appointment.client.phone %></td>
      <td class="btn-group gap-2">
        <%= link_to 'Editar', edit_appointment_path(appointment), class: 'btn btn-warning btn-sm' %>
        <%= button_to 'Excluir', appointment_path(appointment), method: :delete, data: { turbo_confirm: "Você tem certeza?" }, class: 'btn btn-danger btn-sm', form: { data: { turbo_stream: true } } %>
      </td>
    </tr>
  <% end %>
</tbody>

app/views/users/edit.html.erb
<h1>Editando Usuário</h1>

<%= form_with(model: @user, local: true) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone %><br />
    <%= form.text_field :phone, autofocus: true, autocomplete: "phone" %>
  </div>

  <div class="field">
    <%= form.label :password %> <i>(deixe em branco se não quiser alterar)</i>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit "Atualizar" %>
  </div>
<% end %>

<%= link_to 'Voltar', admin_path %>